### ISSUE TITLE
Python interface for ase is missing?

### ISSUE THREAD

**Issue by jkitchin** [atomisticnet/aenet#1]
In an earlier version there was a Python interface that allowed one to use an aenet trained potential in ASE. It seems to be missing in this version. Do you know if the older version still works with this?

**Comment by nartrith** [comment]
HI John,

No, unfortunately the old ASE Python interface is not compatible with aenet
version 2. We are still working on the updated interface.

Nong

**Comment by jkitchin** [comment]
I am going to close this since pull request #4 was merged. Thanks!
