### ISSUE TITLE
Installing python interface error

### ISSUE THREAD

**Issue by vsumaria** [atomisticnet/aenet#11]
I followed all the process in the documentation for the installation. I installed the python interface using -- python setup install --user

But when I try to import ANNCalculator using from aenet.ase_calculator import ANNCalculator in the python script, I get the following error: "core.cpython-36m-x86_64-linux-gnu.so: undefined symbol: AENET_ERR_MALLOC" 

I tried to compile aenet using gfortran_serial and gfortran_mpi, both are giving the same issue. 

Also, does the python interface only work for python3 ?

**Comment by nartrith** [comment]
This does not seem to be a bug.  There has been an email exchange in the aenet forum: http://ann.atomistic.net/forum/?place=msg%2Faenet%2FMioTk2EgZC4%2FvwdukO6wCgAJ
