### ISSUE TITLE
How to generate a .stp file

### ISSUE THREAD

**Issue by wangnumber14** [atomisticnet/aenet#13]
Hello, I want to use aenet to train a model, I see fingerprint.f90 can compute the structural fingerprints.
While, when I use it with a dir including some xsf file, it report a "segment fault" error. When I use it with one xsf file, it will generate some results, not a stp file. How to use it?
Thanks a lot.

As follows:
______________________________________
$$$$ ./fingerprint.x xsf/structure10000136911.xsf 6.5 12 6.5 4 Ti O
 xsf/structure10000136911.xsf          75
 xsf/structure10000136911.xsf          75
 xsf/structure10000136911.xsf          74
 xsf/structure10000136911.xsf          74
 xsf/structure10000136911.xsf          70
 xsf/structure10000136911.xsf          78
 xsf/structure10000136911.xsf          73
 xsf/structure10000136911.xsf          78
 xsf/structure10000136911.xsf          73
 xsf/structure10000136911.xsf          73
 xsf/structure10000136911.xsf          77
 xsf/structure10000136911.xsf          76
xsf/structure10000136911.xsf  1.42661317E+01  1.48715715E+00 -1.10546093E+01 -2.17259282E+00  5.09528968E+00  6.81191796E-02 -1.23834783E+00  1.48251178E+00 -1.43082665E-01 -1.34007727E+00  2.51005362E-01  4.36856773E-01  1.17738736E-01  9.89171875E+01 -1.00225288E+02  1.29628481E+02 -2.65745459E+02  6.70475042E+02 -4.83391464E+00 -3.57385843E-01  3.70342088E+00  4.06425929E-01 -1.64218313E+00  1.56185631E-01  3.10252400E-01 -2.78981747E-01  2.03700063E-01  5.25495597E-02 -5.75246723E-02  6.51295891E-02 -5.73658127E-01  9.05182379E+00 -8.11461593E+00  7.67151255E+00 -1.42835689E+01  3.89613732E+01

$$$$$$ ./fingerprint.x xsf/ 6.5 12 6.5 4 Ti O
Segmentation fault

_________________________________________________________

**Comment by nartrith** [comment]
@wangnumber14 `fingerprint.x` is not used to generate `stp` files. In fact, you have to write the Fingerprint setup files yourself. Please see the `aenet` manual for details: http://ann.atomistic.net/documentation/#invariant-basis-structural-fingerprint
