### ISSUE TITLE
Running in parallel?

### ISSUE THREAD

**Issue by jkitchin** [atomisticnet/aenet#8]
Hi, I have built an mpi version of aenet via:

`make -f makefiles/Makefile.gfortran_mpi`

As far as I can see it worked fine, and I have a new train.x-2.0.3-gfortran_mpi executable. It is not obvious to me it does anything in parallel though. If I run it like this:

`mpirun -np 6 train.x-2.0.3-gfortran_mpi train.in`

I can't tell that it is running on 6 cores, and only energies.test.0  and energies.train.0 are created (I thought perhaps 6 of them might be created).

Is there anything you need to put in the input file, or other thing that is required to run aenet in parallel? Thanks,

**Comment by jkitchin** [comment]
Nevermind. It appears I had to recompile the parallel module, and once I did that, things seem to work fine.

**Comment by nartrith** [comment]
Hi,

The number of parallel processes is written out at the beginning of the
output file. The parallelization works very well for the BFGS method. If
you do not see any speedup and if only the “.0” files were created, maybe
there were old object files around when you compiled aenet. Please try to
“make clean” and recompile.

Best,
Nong

**Comment by jkitchin** [comment]
Thanks Nong. That is exactly what the problem was.
